import { Router, type IRouter } from "express";
import healthRouter from "./health";
import playersRouter from "./players";
import teamsRouter from "./teams";
import tournamentsRouter from "./tournaments";
import matchesRouter from "./matches";
import rankingsRouter from "./rankings";
import newsRouter from "./news";
import mediaRouter from "./media";
import mediaHubRouter from "./media-hub";
import statsRouter from "./stats";
import storageRouter from "./storage";
import communityRouter from "./community";
import seasonsRouter from "./seasons";
import announcementsRouter from "./announcements";
import agentChatRouter from "./agent-chat";
import memberDeviceRouter from "./member-device";
import supportRouter from "./support";
import supportAdminRouter from "./support-admin";
import adsRouter from "./ads";
import hallOfFameRouter from "./hall-of-fame";
import liveRouter from "./live";
import coinsRouter from "./coins";

const router: IRouter = Router();

router.use(healthRouter);
router.use(playersRouter);
router.use(teamsRouter);
router.use(tournamentsRouter);
router.use(matchesRouter);
router.use(rankingsRouter);
router.use(newsRouter);
router.use(mediaRouter);
router.use(mediaHubRouter);
router.use(statsRouter);
router.use(storageRouter);
router.use(communityRouter);
router.use(seasonsRouter);
router.use(announcementsRouter);
router.use(agentChatRouter);
router.use(memberDeviceRouter);
router.use(supportRouter);
router.use(supportAdminRouter);
router.use(adsRouter);
router.use(hallOfFameRouter);
router.use(liveRouter);
router.use(coinsRouter);
// Note: auth routes are mounted directly in app.ts

export default router;
