import { apiUrl } from "@/lib/api";

export interface TranscriptInfo {
  fullName: string;
  phone: string;
  /** Aqoonsi / Account No — included only for eFootball orders, manager side. */
  accountNo?: string | null;
  discord: string;
  price: string;
  orderId: string;
  productName: string;
  date: string;
  status: string;
}

/** Rounded-rectangle path helper (roundRect is unavailable in older browsers). */
function roundRectPath(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number,
  r: number,
) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.arcTo(x + w, y, x + w, y + r, r);
  ctx.arcTo(x + w, y + h, x + w - r, y + h, r);
  ctx.lineTo(x + r, y + h);
  ctx.arcTo(x, y + h, x, y + h - r, r);
  ctx.arcTo(x, y, x + r, y, r);
  ctx.closePath();
}

function drawRow(ctx: CanvasRenderingContext2D, label: string, value: string, y: number): number {
  ctx.textAlign = "left";
  ctx.fillStyle = "rgba(226,232,240,0.55)";
  ctx.font = '700 15px "Segoe UI", system-ui, sans-serif';
  ctx.fillText(label.toUpperCase(), 72, y);
  ctx.fillStyle = "#f1f5f9";
  ctx.font = '800 26px "Segoe UI", system-ui, sans-serif';
  ctx.fillText(value, 72, y + 34);
  return y + 78;
}

/**
 * Generate the WG-SHOP order transcript as a real PNG data URL, drawn from the
 * actual order data (never hard-coded values).
 */
export async function generateTranscriptPng(info: TranscriptInfo): Promise<string> {
  const W = 860;
  const H = info.accountNo ? 1120 : 1050;
  const canvas = document.createElement("canvas");
  canvas.width = W;
  canvas.height = H;
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Canvas is not supported in this browser");

  // Background + subtle glow accents
  ctx.fillStyle = "#070b14";
  ctx.fillRect(0, 0, W, H);
  const glow = ctx.createRadialGradient(W - 80, 90, 10, W - 80, 90, 420);
  glow.addColorStop(0, "rgba(134,239,172,0.16)");
  glow.addColorStop(1, "rgba(134,239,172,0)");
  ctx.fillStyle = glow;
  ctx.fillRect(0, 0, W, H);

  // Main card
  ctx.fillStyle = "#0d1626";
  roundRectPath(ctx, 36, 36, W - 72, H - 72, 20);
  ctx.fill();
  ctx.strokeStyle = "#22304f";
  ctx.lineWidth = 2;
  ctx.stroke();

  // Logo (best effort — skipped if it cannot load)
  await new Promise<void>((resolve) => {
    const logo = new Image();
    logo.onload = () => {
      ctx.save();
      roundRectPath(ctx, 72, 74, 64, 64, 12);
      ctx.clip();
      ctx.drawImage(logo, 72, 74, 64, 64);
      ctx.restore();
      resolve();
    };
    logo.onerror = () => resolve();
    logo.src = apiUrl(`${import.meta.env.BASE_URL}logo.jpg`);
  });

  // Branding header
  ctx.textAlign = "left";
  ctx.fillStyle = "#86efac";
  ctx.font = '900 40px "Segoe UI", system-ui, sans-serif';
  ctx.fillText("WG-SHOP", 156, 112);
  ctx.fillStyle = "rgba(226,232,240,0.6)";
  ctx.font = '800 17px "Segoe UI", system-ui, sans-serif';
  ctx.fillText("W A R Y A A   G A M I N G", 158, 136);
  ctx.textAlign = "right";
  ctx.fillStyle = "#facc15";
  ctx.font = '900 22px "Segoe UI", system-ui, sans-serif';
  ctx.fillText("ORDER TRANSCRIPT", W - 72, 112);

  // Divider
  ctx.strokeStyle = "#22304f";
  ctx.beginPath();
  ctx.moveTo(72, 170);
  ctx.lineTo(W - 72, 170);
  ctx.stroke();

  // Rows
  let y = 218;
  y = drawRow(ctx, "Full Name", info.fullName, y);
  y = drawRow(ctx, "Number", info.phone, y);
  if (info.accountNo) y = drawRow(ctx, "Account No", info.accountNo, y);
  y = drawRow(ctx, "Discord Username", info.discord, y);
  y = drawRow(ctx, "Price", info.price, y);

  // Second card for order meta
  ctx.fillStyle = "rgba(34,48,79,0.35)";
  roundRectPath(ctx, 52, y - 10, W - 104, 190, 14);
  ctx.fill();
  let y2 = y + 28;
  y2 = drawRow(ctx, "Order ID", info.orderId, y2);
  y2 = drawRow(ctx, "Product", info.productName.slice(0, 34), y2);

  const metaY = y2;
  ctx.textAlign = "left";
  ctx.fillStyle = "rgba(226,232,240,0.55)";
  ctx.font = '700 15px "Segoe UI", system-ui, sans-serif';
  ctx.fillText("DATE", 72, metaY);
  ctx.fillStyle = "#f1f5f9";
  ctx.font = '800 22px "Segoe UI", system-ui, sans-serif';
  ctx.fillText(info.date, 72, metaY + 28);
  ctx.textAlign = "right";
  ctx.fillStyle = "rgba(226,232,240,0.55)";
  ctx.font = '700 15px "Segoe UI", system-ui, sans-serif';
  ctx.fillText("STATUS", W - 72, metaY);
  ctx.fillStyle = "#86efac";
  ctx.font = '900 24px "Segoe UI", system-ui, sans-serif';
  ctx.fillText(info.status.toUpperCase(), W - 72, metaY + 28);

  // Footer
  ctx.textAlign = "center";
  ctx.fillStyle = "rgba(148,163,184,0.5)";
  ctx.font = '700 14px "Segoe UI", system-ui, sans-serif';
  ctx.fillText("Generated by WG-SHOP — Waryaa Gaming Official Marketplace", W / 2, H - 58);

  return canvas.toDataURL("image/png");
}
